### PR TITLE
Added 3 variations of Prismarine Stairs [UPDATED]

### PR DESCRIPTION
**Pull request by DroidMTPM**
I added **_Prismarine Stairs_**, **_Prismarine Brick Stairs_**, and **_Dark Prismarine Stairs_**.

I also renamed the class to _PrismarineStairsBlock_, and I replaced **$this** with **new Placeholder($this)** when using setBlock in the block's class.

### CODE REVIEW

**Comment by officialjustine** [comment]
Can you add Bamboo too?

**Review by xSuperr — APPROVED** [review]
Looks nice, I will test it tomorrow then merge if there are no problems!

**Comment by DroidMTPM** [comment]
> Looks nice, I will test it tomorrow then merge if there are no problems!

Sounds good!

> Can you add Bamboo too?

Yeah, I'll continue adding more blocks after the merge

**Comment by xSuperr** [comment]
Merged.

**Comment by YaNIND** [comment]
add Item Totem can use in offhand

**Pull request merged**
