### PR TITLE
Fix Inventory Block Register bug

### PR DESCRIPTION
**Pull request by supercrafter333**

### CODE REVIEW

**Comment by xSuperr** [comment]
What bug does this exactly fix? I've never found an issue with the creative inventory and I'm curious.

**Comment by supercrafter333** [comment]
This pr can fix inventory register bugs, when you Register some Special Blocks.

**Comment by xSuperr** [comment]
But what exactly was the bug? The items did not show up, they wouldn't work, ect.

**Comment by xSuperr** [comment]
Closing this because in the next version a fix somewhat like this is added, but there are errors with this fix.

**Pull request closed without merging**
