### PR TITLE
Add Trapdoor, all strairs ans polished basalt

### PR DESCRIPTION
**Pull request by HugoLeBoss91**

### CODE REVIEW

**Review by xSuperr — CHANGES_REQUESTED** [review]
I would like the class names for the files changed to WoodenStairBlock, StoneStairBlock, OtherStairBlock, and Trapdoor class renamed to Trapdoor Block. I would also like the Main file to be better formatted (They aren't all in line). If those changed are made, and once poggit gets back online I will merge.

**Comment by HugoLeBoss91** [comment]
Ok

**Comment by HugoLeBoss91** [comment]
Now is good ?

**Comment by xSuperr** [comment]
Yeah, can you test if everything is working? Once poggit comes back online I will merge.

**Comment by HugoLeBoss91** [comment]
I have already tested everything and everything works perfectly

**Comment by xSuperr** [comment]
Ok fix the conflicting files, and apparently poggit-ci detects a syntax error in the file, if you could look into that and fix the issue then I can merge.

**Comment by HugoLeBoss91** [comment]
Now is good ?

**Comment by xSuperr** [comment]
VanillaBlocks.php still needs to have the register functions for the two log blocks (Check main file of my plugin), and you removed the register function for your trapdoor blocks.

**Comment by HugoLeBoss91** [comment]
Oups

**Comment by HugoLeBoss91** [comment]
Normally, the "main" brache is good

**Comment by xSuperr** [comment]
Then please open a new pull request on the main branch of your fork.

**Comment by HugoLeBoss91** [comment]
The Test branch work to

**Pull request merged**
